opcache.enable=1
opcache.enable_cli=0
opcache.validate_timestamps=1
opcache.revalidate_freq=2
memory_limit=512M
max_execution_time=300
default_socket_timeout=300
upload_max_filesize=16M
post_max_size=16M
date.timezone=UTC
expose_php=0
display_errors=Off
log_errors=On
error_reporting=E_ALL & ~E_DEPRECATED
